version: "3.8"

services:
  php:
    container_name: hackathon_api
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html    
    env_file:
      - .env

  nginx:
    container_name: hackathon_nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html    
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

      